# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd6188f74b1f998943d7b7f6c411f1c5519a11cb067e677818c5d50d3794900aff71a42d8b5fa06b8571e20419ca82e636a567582ad31751f01863359bc60962

test:
  secret_key_base: 062a684eac45ca050c378aeaaecff69bcb9b7c20ae23a2c9aad8c2df693f767ff923806b9f50339f54a0710eb8dc509161ce4ab986cdf3e44dceae5163889043

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


docker:
  secret_key_base: 062a684eac45ca050c378aeaaecff69bcb9b7c20ae23a2c9aad8c2df693f767ff923806b9f50339f54a0710eb8dc509161ce4ab986cdf3e44dceae5163889043
